plugins {
    id 'com.android.application'
}

android {
    namespace 'com.neksus.eld.driver'
    compileSdk 35

    defaultConfig {
        applicationId 'com.neksus.eld.driver'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '0.3.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
